import type { Config } from 'tailwindcss'

// Configuración de Tailwind CSS con el design system "Silicon Architect"
export default {
    darkMode: 'class',
    content: [
        './components/**/*.{vue,js,ts}',
        './layouts/**/*.vue',
        './pages/**/*.vue',
        './plugins/**/*.{js,ts}',
        './app.vue',
    ],
    safelist: [
        'hidden',
        'md:flex',
        'md:block',
        'md:hidden',
        'lg:flex',
        'lg:block',
        'lg:hidden',
        'lg:grid-cols-12',
        'lg:col-span-8',
        'lg:col-span-4',
        'md:flex-row',
        'md:text-8xl',
        'md:text-xl',
        'md:grid-cols-2',
        'lg:grid-cols-3',
        'lg:grid-cols-4',
    ],
    theme: {
        extend: {
            colors: {
                'background': '#091421',
                'surface': '#091421',
                'surface-dim': '#091421',
                'surface-bright': '#303a48',
                'surface-container-lowest': '#050f1c',
                'surface-container-low': '#121c2a',
                'surface-container': '#16202e',
                'surface-container-high': '#212b39',
                'surface-container-highest': '#2b3544',
                'surface-variant': '#2b3544',
                'on-surface': '#d9e3f6',
                'on-surface-variant': '#c1c7d2',
                'on-background': '#d9e3f6',
                'primary': '#a3c9ff',
                'primary-container': '#3272b8',
                'primary-fixed': '#d3e3ff',
                'primary-fixed-dim': '#a3c9ff',
                'on-primary': '#00315c',
                'on-primary-container': '#f2f5ff',
                'on-primary-fixed': '#001c39',
                'on-primary-fixed-variant': '#004882',
                'secondary': '#ffb691',
                'secondary-container': '#ea6b15',
                'secondary-fixed': '#ffdbcb',
                'secondary-fixed-dim': '#ffb691',
                'on-secondary': '#552100',
                'on-secondary-container': '#4a1c00',
                'on-secondary-fixed': '#341100',
                'on-secondary-fixed-variant': '#783100',
                'tertiary': '#4cd6ff',
                'tertiary-container': '#007a96',
                'tertiary-fixed': '#b7eaff',
                'tertiary-fixed-dim': '#4cd6ff',
                'on-tertiary': '#003543',
                'on-tertiary-container': '#e7f7ff',
                'on-tertiary-fixed': '#001f28',
                'on-tertiary-fixed-variant': '#004e60',
                'outline': '#8b919c',
                'outline-variant': '#414751',
                'error': '#ffb4ab',
                'error-container': '#93000a',
                'on-error': '#690005',
                'on-error-container': '#ffdad6',
                'inverse-surface': '#d9e3f6',
                'inverse-on-surface': '#27313f',
                'inverse-primary': '#1760a5',
                'surface-tint': '#a3c9ff',
            },
            fontFamily: {
                'headline': ['Space Grotesk', 'sans-serif'],
                'body': ['Plus Jakarta Sans', 'sans-serif'],
                'label': ['Space Grotesk', 'sans-serif'],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                'lg': '0.25rem',
                'xl': '0.5rem',
                'full': '0.75rem',
            },
        },
    },
    plugins: [],
} satisfies Config
